project:
  type: website

website:
  title: "AutoML Eindhoven"
  navbar:
    background: light
    logo: "images/logo.png"
    collapse-below: lg
    left:
      - index.qmd
      - text: "Research"
        menu: 
          - file: projects.qmd
          - file: publications.qmd
      - software.qmd
      - people.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto