project:
  type: website

website:
  title: "TU/e AutoML Lab"
  navbar:
    background: light
    logo: "images/logo.png"
    collapse-below: lg
    left:
      - index.qmd
      - projects/projects.qmd
      - publications/publications.qmd
      - software/software.qmd
      - people/people.qmd
      - join/join.qmd
    right:
      - icon: github
        href: https://github.com/openml-labs/website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
